# Generated by Django 5.1 on 2025-06-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('porcentagem', 'Porcentagem'), ('preco_fixo', 'Preço Fixo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('produto', models.ManyToManyField(to='produtos.produto')),
            ],
        ),
    ]
