# Generated by Django 5.1 on 2025-06-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
